// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import * as dotenv from "dotenv";
// Prisma CLI doesn't read .env.local (that's Next.js-only).
// Load it explicitly so DATABASE_URL is available for db push / migrate.
dotenv.config({ path: ".env.local" });
dotenv.config(); // fallback to .env for anything not in .env.local
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env.DATABASE_URL ?? "",
  },
});
